/***************
 * POKEMONS
 ***************/
export const LOAD_POKEMONS = 'LOAD_POKEMONS';
export const LOAD_POKEMONS_SUCCEEDED = 'LOAD_POKEMONS_SUCCEEDED';
export const LOAD_POKEMONS_FAILED = 'LOAD_POKEMONS_FAILED';

export const LOAD_POKEMON = 'LOAD_POKEMON';
export const LOAD_POKEMON_SUCCEEDED = 'LOAD_POKEMON_SUCCEEDED';
export const LOAD_POKEMON_FAILED = 'LOAD_POKEMON_FAILED';

export const CLEAR_STATE = 'CLEAR_STATE';